### ISSUE TITLE
License

### ISSUE THREAD

**Issue by moritonal** [siriusastrebe/syc#1]
Hi Sirius

Was writing my own version of this for a side-project, then found your (better) version :)

I was wondering what the license is for this project?

**Comment by siriusastrebe** [comment]
'ey, sorry bout the delayed response.

I'll license it MIT.

If you're interested enough to help with the code, I'd be more than happy to give you access. I have a couple of changes to the api I want to make, but you can find the latest code in the branch named 'latest'
